name: run_on_pr_to_master
on:
  push:
    branches:
      - master
    paths:
      - 'python-env-var-parser/**'

jobs:
  execute:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout the repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4

      - name: execute python-env-var-parser
        run: |
          output=$(python python-env-var-parser/parser.py)
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=log::$output"
        id: step-execute-parser

      - name: print parser output
        run: echo "${{ steps.step-execute-parser.outputs.log }}"

      - name: check environment variable status
        run: |
          if [[ -z "${ENV_VAR}" ]]
          then
            echo "Environmental variable is set via Python script and its value is ${ENV_VAR}"
          else
            echo "Environmental variable is not set. Exiting..."
            exit 1
          fi


